### ISSUE TITLE
"Critical error" message using tsml_pdf commands

### ISSUE THREAD

**Issue by troycpb** [code4recovery/12-step-meeting-list#399]
**Describe the bug**
When following links to access a pdf of the meeting list (which otherwise appears to be functioning normally in all other capacities), users get an error page which reads, "There has been a critical error on your website.

Learn more about debugging in WordPress."

**To Reproduce**
1. Go to https://aa-palmbeachcounty.org/new/wp-admin/admin-ajax.php?action=tsml_pdf
2. Or any modified version of the link, like https://aa-palmbeachcounty.org/new/wp-admin/admin-ajax.php?action=tsml_pdf&width=8.5
3. ???

**Expected behavior**
This usually presents a simple PDF meeting list that the user can view in a web browser or download.  It's really great!

**Screenshots**
![image](https://user-images.githubusercontent.com/86694983/123884110-6c0a7800-d918-11eb-85d7-2b4e564c088b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Version 91.0.4472.124 (Official Build) (64-bit)

**Additional context**
Our webhost had to do a PHP reinstallation after their PHP upgrade wizard failed.  Maybe this is causing the ajax command to fail?  I am not experienced with or knowledgeable about ajax.  Also, we're now running PHP 7.4 - maybe that is causing the problem?

Thank you for your service creating this amazing plugin.  It is incredibly useful for our community.  We weren't relying on the PDF feature, as I had only very recently introduced a link to the pdf version of the list, so none of our users miss this function just yet!  Would love to get to the bottom of what's causing it, though.

Thanks,

Troy

**Comment by tech2serve** [comment]
Hey @troycpb,

I'm getting an error with PHP 7.4, but didn't with a PHP 7.3. If you're able to get your hosting platform to roll you back to 7.3, I think that will resolve your issue. I realize that is kind of a long shot but it might get you up and running with a PDF quicker. 

You also might try the 12 Step Meeting PDF plugin (not affiliated with us) to see if that works better.

We'll add this issue to our work list.

Tim

**Comment by brianw-area24** [comment]
I installed PHP 7.4 on my new computer tonight, to look at this issue. Like @tech2serve, this ran for me when using PHP 7.3 but not with 7.4.

It was giving me a Warning and and Error. These were both coming from a third party pdf library that we include in the plugin. so I got looking at that library, and noticed the fix for the warning. It was a one line fix where it forced a variable to be an integer. This simple fix seems to have fixed both the Warning and the Error, and allows the PDF's to generate using PHP 7.4.

I've included this patch in a commit in the bw/attendance branch, so it should be included in the next minor release of TSML, and this feature will then run with PHP 7.4.

@tech2serve The library is on github, under tecnickcom/TCPDF. We may want to do more testing with the update of this library, and include the updated version in a future version of TSML, instead of the little change I'm making now...

Brian W

**Comment by troycpb** [comment]
Hi all,

I'm currently running 3.11.3 but still experiencing this issue.  Is it still a known bug or is there a configuration issue on my end that might be the problem?

**Comment by joshreisner** [comment]
Hi @troycpb yes I think it should be fixed in the next release. If you want to help us Q/A test it you can [download it here](https://github.com/code4recovery/12-step-meeting-list/archive/refs/heads/develop.zip)

**Comment by joshreisner** [comment]
Complete with release of `3.12`

**Comment by troycpb** [comment]
Hi Josh,

Went ahead and did that but still getting the same message with no additional error message unfortunately.

**Comment by troycpb** [comment]
Hi @97eighty !  Very sorry for the delayed reply, it's been a very busy month on my end!  I'm not familiar with the PDF generator service specifically - I'm sort of a Wordpress novice in general, and tsml_pdf function by glancing at another site's menus.  Any chance you could point me in the direction of where I can find the commands for the new PDF generator service, and how I might link our website's users to the function?

**Comment by 97eighty** [comment]
@troycpb Troy, instructions on the PDF generator service can be found on our project page: https://github.com/code4recovery/pdf. The actual service is here: https://pdf.code4recovery.org
